### ISSUE TITLE
Bookmarks disappeared after VS Code upgrade

### ISSUE THREAD

**Issue by wedeluxe** [alefragnani/vscode-bookmarks#174] opened 2019-01-16 13:02 UTC
### Specs:
Bookmarks 10.1.0
"bookmarks.saveBookmarksInProject": false

### Problem:
After upgrading VS Code from version 1.27.2 to version 1.30.2 all bookmarks in all files have disappeared.

In detail:

1. I've been using VS Code 1.27.2 and Bookmarks 10.1.0 (for weeks without any kind of issue)
2. Upgraded VS Code from version 1.27.2 to version 1.30.2
3. When running VS Code all bookmarks in all files didn't show up

### Finally:
Hopefully, the bookmarks are not gone for good.
Is there anything I can do to bring them back?
Like running a conversion tool or tweaking a setting that I'm not aware of?

Right now I have no clue what might went wrong.

**Comment by alefragnani** [comment] 2019-01-16 21:13
Hi @wedeluxe ,

Are you sure you did opened _the same folder/project_? I mean, opening _some folder_ and opening _some workspace that contains that folder_ are two different things. Both store the bookmarks in different places in VS Code internals (when using `bookmarks.saveBookmarksInProject": false`.

BTW, if this issue happened after you upgraded VS Code (not the extension) I suggest you to report/ask this in VS Code repo, because the extension itself don't do anything when VS Code upgrades. Maybe something has been "restarted" by VS Code itself when upgrading.

When I say VS Code internals, I'm talking about Chrome structure. Look at `Toggle Developer Tools / Application / Local Storage / file://`. You could filter by `alefragnani.Bookmarks` and search for your project folder, like the print below. The bookmarks are stored there and you can Copy it.

![image](https://user-images.githubusercontent.com/3781424/51278711-79d71780-19c2-11e9-843a-ff1b9d87f9cc.png)


Hope this helps

**Comment by wedeluxe** [comment] 2019-01-17 21:35
I'm absolutely sure to have opened the very same workspaces/folders/projects.

And this is why: When using VS Code I always have 8-10 (or even more) windows open, with all these windows showing different workspaces. Thus I always have my most frequently used projects up and running and within reach of a few keystrokes. Starting a new VS Code session means it automatically opens all windows (and their workspaces) which I had open when closing the previous session.

Thanks for pointing towards VS Code internals and the Developer Tools. Didn't know about that.

I went there and filtered the entries as you suggested. Here's the results:

- Some entries were completely wiped out:
`{"bookmarks":"[]"}`

- Many entries have a prefix I wouldn't have expected in there (`...BookmarkEmitter` - stuff). An example:

        {"bookmarks":"{\"onDidClearBookmarkEmitter\":{},\"onDidClearAllBookmarksEmitter\":{},\"onDidAddBookmarkEmitter\":{},\"onDidRemoveBookmarkEmitter\":{},\"onDidUpdateBookmarkEmitter\":{},\"bookmarks\":[]}"}	

- There still are bookmarks in the database. But they are not displayed in the open windows (workspaces). An Example:

        {"bookmarks":"[{\"path\":\"/wdlx/bauplatz/projects/clone/python/clone/draft.py\",\"bookmarks\":[{\"line\":42,\"column\":1,\"label\":\"\"},{\"line\":484,\"column\":1,\"label\":\"\"}]}]"}

**Comment by alefragnani** [comment] 2019-01-17 22:08
Hi @wedeluxe ,

About the internals:

- `{"bookmarks":"[]"}`does not mean _wiped out_, but an empty entry. Even if you don’t use bookmarks for a folder/workspace, it will _store_ that. 
- `onDidClearBookmarkEmitter....` is the _old format_, prior to version which added Column Number and Labels
- The others, should show when you open that folder/workspace. Unfortunately, it’s not easy to identify a workspace using that _pseudoname_ which VSCode uses in Developer Tools.

Hope this helps

**Comment by wedeluxe** [comment] 2019-01-19 18:04
> * `{"bookmarks":"[]"}`does not mean _wiped out_, but an empty entry. Even if you don’t use bookmarks for a folder/workspace, it will _store_ that.

Of course this is an empty entry. But the workspace which is empty now had several hundred bookmarks in it before. This is why I called it _wiped out_. Essentially the bookmarks were wiped out by a serious bug.

> * The others, should show when you open that folder/workspace.

Well, the other workspaces already are open. Despite having bookmark entries in the database, the bookmarks are not displayed in the corresponding windows.

Tried to solve this by:

+ Press the _Refresh_ button in the Bookmarks Explorer. That has no effect, bookmarks still are not displayed (not in the explorer, not in the editor).
+ (Just as a reminder: I have 8-10 windows/workspaces open)
  Then I went window by window.
  + Close the window.
  + Then open a new window.
  + Open that workspace in the new window.
  + Result: bookmarks still are not recognized/displayed.

> Unfortunately, it’s not easy to identify a workspace using that _pseudoname_ which VSCode uses in Developer Tools.

I assume that when you say _pseudoname_ you mean those hex identifiers. Actually, I don't have many of those, just in four workspace keys. The other 15 workspace keys are human readable paths.

**Comment by aplatypus** [comment] 2019-11-01 03:11
It is November today.

This is still a problem on large files.  

It is lamentable too because when people only had a few megabytes of memory, editors could always handle very, very large files.  Becasue they didnt rely on loading everything into memory

```
Version: 1.39.2
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:33:40.634Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Linux x64 5.0.7-050007-generic
```

**Comment by alefragnani** [comment] 2020-01-26 13:46
Hi @aplatypus , I think your problem is not related to the original issue, but #31 instead, which is caused by VS Code itself, as [commented here](https://github.com/alefragnani/vscode-bookmarks/issues/31#issuecomment-241591416).

I remember the VS Code team made some improvements to load larger files, but the extensions still aren't fully _enabled_ to work with those files, so we are out of luck, sorry.

**Comment by alefragnani** [comment] 2021-06-28 23:40
I'm closing this issue because no new comments/reports has been added for a long time. Unfortunately I couldn’t reproduce the error back then, but I suppose it would be a combination of extension and VSCode updates. 

Thankfully, no new reports for a long time.

**Closed by alefragnani** 2021-06-28 23:40 UTC
Labels: caused by vscode, question
