### ISSUE TITLE
Bookmark moving off original line

### ISSUE THREAD

**Issue by murraycollingwood** [alefragnani/vscode-bookmarks#168] opened 2018-12-23 22:10 UTC
I normally add bookmarks where I have function names.  However sometime during editing the bookmark seems to move off the function name.  Is there some editing functions I shouldn't be using in order for the bookmarks to stay anchored to the correct line?

I'm on OSX 10.13.6 and VS Code 1.30.1 and Bookmarks 10.0.0

![image](https://user-images.githubusercontent.com/5810216/50387903-5080ee00-076c-11e9-926d-282b167cbaa3.png)

**Comment by alefragnani** [comment] 2018-12-24 16:14
Hi @murraycollingwood 

The bookmarks _should_ stay glued to the source code (sticky behavior), not the line number itself, automatically. So, you don’t need to do anything else to it move up or down when you update your code.

I’m wondering, aren’t you facing #116 or #118? If not, then you may have found a new issue with the sticky behavior that needs to be addressed.

Hope this helps

**Comment by murraycollingwood** [comment] 2018-12-25 04:10
I don't use the 'prettier' option, however I do sometimes 'undo' changes.
Let me monitor it and see if I can isolate the problem for you.

**Comment by alefragnani** [comment] 2019-01-06 19:09
Hi @murraycollingwood ,

If you are using `Move Line Up` or `Move Line Down` commands, you could be facing #108. Fortunately, this has been fixed with #136 , which will be released tomorrow (version 10.1.0).

Let me know if it has fixed your scenario, after the update.

**Comment by FSLobao** [comment] 2019-02-08 11:39
Same issue for me

**Comment by alefragnani** [comment] 2019-03-20 16:27
Hi @murraycollingwood  @FSLobao,

Are you still facing this issue? Is it related to **Undo** or **Formatters**? If not, please give me the steps that I should follow to reproduce the issue.

I'm revisiting the _sticky_ feature, and would like to see if it is still happening.

Thank you

**Comment by FSLobao** [comment] 2019-03-20 17:22
Did a few tests and everything is working perfectly with the sticky feature.

Thanks and regards.

**Comment by code4bones** [comment] 2019-08-21 12:45
same issue...

**Comment by JoshLambda** [comment] 2019-08-31 07:29
I had the same issue. 
I switched setting `Use Workaround For Formatters` to false (it was enabled for unknown reason), bookmark stickiness is working again.

**Comment by mig8447** [comment] 2020-04-27 04:46
I've been having the same issue. The extension idea is wonderful, but I stopped using it because bookmarks move one or two lines sometimes

**Comment by pyramid-johng** [comment] 2020-08-11 15:04
here's a hint:  extension must track the `onDidChangeTextDocument` event, and make incremental updates to its line numbers to stay "in sync" with changes, otherwise it won't ever work right.  the "type" of file should not matter to the extension, as long as it's text in a range in a document.

ran into the exact same problems in an extension i am building myself, and in fact, anything using decorations will have the same issues, unless it is doing 100% document re-scans on every TD update (yak).

I'm getting ready to turn this extensions off; i'm spending more time resetting bookmarks than work.  i use no formatters whatsoever only manual edits and invocation of "format document" every so often.

**Comment by alefragnani** [comment] 2020-08-11 21:19
Hi @pyramid-johng ,

That's exactly how the extension works, as you can see here:

https://github.com/alefragnani/vscode-bookmarks/blob/a6616c782dddd6059acde16c94c3139e9cdd2e4f/src/extension.ts#L98

The problem is to correctly handle the different kind of changes that this event fires, and the different settings that interact with it. For regular scenarios the extension works perfectly, but yes, `Undo` operations sometimes are a mess, and `Formatters` are not supported. Formatters like prettier or manually called, appears to do the same, and yes, is a complex issue if you don't have a high level API.

Sometime ago I found an issue in VS Code repo asking for a _proper API_ (don't remember if is the same as yours), but no ETA from VS Code team. 

It's on my radar, and I would like to return to this issue soon, but no ETA yet.

Hope this helps

**Comment by os-ia** [comment] 2021-03-16 08:26
I am facing the same issue, it seems like the bookmark sticks to the line instead of the source code.

Context: 
- VSCode 1.54.3 x64 (`2b9aebd5354a3629c3aba0a5f5df49f43d6689f8`)
- Language: Python (3.7.9)
- OS: Darwin 20.2.0 (macOS Big Sur)
- No formatters active

**Comment by elder-n00b** [comment] 2021-04-16 01:02
Was this fixed just now or is it an Heisenbug? 

I came to confirm the issue, did a little testing, and poof I can't reproduce it anymore.  

Testing included enabling the workaround (didn't help at all) then resetting it, restarting the extensions host, restarting VSCode, uninstalling and reinstalling the extension (hence I wonder if it was updated meanwhile), all the while setting bookmarks and editing a few different file types.  
When I tried with a plain text I noticed the problem was gone, then tried a shell script and no problem, went back to the source code files where it used to happen all the time and it now works.  
I then tried quitting and restarting VSCode again and it still works.  
Too bad I did all this quite randomly so I can't tell the exact sequence of the operations.

I have no code formatter installed but quite a few other extensions.

I will update if it shows up again.

Version: 1.55.2
Commit: 3c4e3df9e89829dce27b7b5c24508306b151f30d
Date: 2021-04-13T09:36:32.643Z
Electron: 11.3.0
Chrome: 87.0.4280.141
Node.js: 12.18.3
V8: 8.7.220.31-electron.0
OS: Darwin x64 15.6.0
macOS: 10.11.6

**Comment by thelegend09** [comment] 2021-05-04 21:01
Same here as post above. The bookmark sticks to the line instead of the code.

I tried with and without the Workaround For Formatters, and yet the problem remains. (I'm not using any formatter.)

(Using VSCode 1.55.2 on my Windows 10 19042.928.)

**Comment by justKD** [comment] 2021-05-06 21:33
1 - Toggle a bookmark on.
2 - Add a line above the bookmark. The bookmark is sticky and moves down.
3 - Undo action. The bookmark is sticky and moves up.

1 - Toggle a bookmark on.
2 - Add TWO lines above the bookmark. The bookmark is sticky and moves down.
3 - Now undoing will displace the bookmark incorrectly by ONE line. The bookmark is "correctly" sticky for the second undo action.
4 - Repeat step three with 3, 4, 5, etc. empty lines. The undo stack is always correct for just the LAST new line.

It seems there's an underlying problem with how undo actions are being counted.
I am using prettier, but workaround option is FALSE.

**Comment by thelegend09** [comment] 2021-05-07 20:24
> Same here as post above. The bookmark sticks to the line instead of the code.
> I tried with and without the Workaround For Formatters, and yet the problem remains. (I'm not using any formatter.)
> (Using VSCode 1.55.2 on my Windows 10 19042.928.)

Finally I got it to work!!!!! My steps:

1. I uninstalled the extension.
2. I uninstalled VS Code using [the free version of Revo Uninstaller](https://www.revouninstaller.com/revo-uninstaller-free-download/) and made sure to delete the registry keys linked to it.
3. I rebooted the computer. Just in case.
4. I reinstalled VS Code. (I redownloaded it, just in case.)
5. I reinstalled the extension.

Everything works flawlessly since. Hurray!

**Comment by defenestrateddefense** [comment] 2021-06-29 18:12
> 1 - Toggle a bookmark on.
> 2 - Add a line above the bookmark. The bookmark is sticky and moves down.
> 3 - Undo action. The bookmark is sticky and moves up.
> 
> 1 - Toggle a bookmark on.
> 2 - Add TWO lines above the bookmark. The bookmark is sticky and moves down.
> 3 - Now undoing will displace the bookmark incorrectly by ONE line. The bookmark is "correctly" sticky for the second undo action.
> 4 - Repeat step three with 3, 4, 5, etc. empty lines. The undo stack is always correct for just the LAST new line.
> 
> It seems there's an underlying problem with how undo actions are being counted.
> I am using prettier, but workaround option is FALSE. If I set the option to TRUE, sticky doesn't work at all.

I can replicate this issue on my end, and I do not use prettier

**Closed** 2021-09-02 23:16 UTC
Labels: bug, sticky
