### ISSUE TITLE
Copying a file loses the bookmarks

### ISSUE THREAD

**Issue by Rumpick** [alefragnani/vscode-bookmarks#271] opened 2020-02-21 22:12 UTC
I tried looking through all issues that mention the word Copy, didn't see mention of this so thought I would open an issue.

I have a template document all setup with Bookmarks, but when I create a copy of that file in VS Code, all the bookmarks are gone in the new document. Even if I use "Save As" to save a copy of the file as a new name, the bookmarks don't carry with it.

Is there a way to support this?

**Comment by alefragnani** [comment] 2020-02-25 23:59
Hi @Rumpick ,

The bookmarks are _relative to the file path_, not the _file content_. When you duplicate/copy their contents, their bookmarks are not copied/moved to the new file. The same happens when you copy lines inside the same file. No matter if some of the lines has bookmarks, the extension does not _duplicates_ these bookmarks. So, right now, the extension is working _as designed_.

I’m not sure I have seen any other editor/IDE copying the bookmarks when you copy the file contents, neither pieces of the file. I wonder how it could deal with _partial copy_ (select a few lines and use Copy/Paste). Could you say which editor/IDE you experienced this behavior, so I could take some inspiration for an enhancement?

Thank you

**Comment by alefragnani** [comment] 2020-04-03 23:59
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Closed by alefragnani** 2020-04-03 23:59 UTC
Labels: enhancement, need more info
