### ISSUE TITLE
mark jump one line

### ISSUE THREAD

**Issue by rmlSardinha** [alefragnani/vscode-bookmarks#187] opened 2019-02-23 11:51 UTC
some lines above a mark, do the following sequence

ctrl + enter
ctrl + enter
ctrl + z

the marking below will skip a line

**Comment by rmlSardinha** [comment] 2019-02-23 11:55
and if you use several enter, when using the ctrl+z, marking jumps multiple lines

**Comment by alefragnani** [comment] 2019-02-27 21:11
Hi @rmlSardinha ,

Probably a duplicate of (or related to) #116 . 

Thanks for reporting

**Closed** 2019-02-27 21:11 UTC
Labels: bug, duplicate, sticky
