### ISSUE TITLE
How to disable release note on vscode startup

### ISSUE THREAD

**Issue by serenedu** [alefragnani/vscode-bookmarks#297] opened 2020-05-10 05:19 UTC
Like this extension, hope there's a way to turn release note off.

**Comment by skoshy** [comment] 2020-05-11 14:40
Agreed, this has been mentioned here (https://github.com/alefragnani/vscode-bookmarks/issues/175). Please allow us to have an option to disable these popups from showing up when the extension is updated.

**Comment by alefragnani** [comment] 2020-05-13 21:48
I’m glad to know you like the extension, but I’m closing this issue as a duplicate of #175 . As described there, this window only appears on updates (not patches).

I’ll post some comments there latter, so if you are interested in follow the subject, I suggest you to subscribe/comment there.

Thank you

**Closed by alefragnani** 2020-05-13 21:48 UTC
Labels: duplicate
