### ISSUE TITLE
[BUG] - Even after uninstalling/reloading/reinstalling Bookmarks, entries are present in Bookmarks sidebar that don't exist

### ISSUE THREAD

**Issue by daniel347x** [alefragnani/vscode-bookmarks#481] opened 2021-11-03 23:30 UTC
**Environment/version**

- Extension version: **13.2**
- VSCode version: **1.59.0**
- OS version: **Windows 10**

**Steps to reproduce**

1. Uninstall Bookmarks extension
2. Quit Visual Code
3. Run Visual Code
4. Install Bookmarks Extension
5. Open Bookmarks sidebar

At this point, I still see two "zombie" entries present:

![image](https://user-images.githubusercontent.com/309746/140232652-db998931-00a4-44bc-beaf-e2854723d10b.png)

When you click on one of the zombies, it DOES take you to those lines of code, but there is no bookmark present (there is no 'bookmark' icon in the gutter):

![image](https://user-images.githubusercontent.com/309746/140232685-42ccec52-581b-4a8c-a34b-93acf23399ab.png)

If you add a bookmark at that same line of code, a new entry appears in the bookmark sidebar (duplicating the zombie entry):

![image](https://user-images.githubusercontent.com/309746/140232751-3f1aa1dd-6707-4f90-9330-755a96cbed65.png)

...and now you do see the 'bookmark' icon in the gutter:

![image](https://user-images.githubusercontent.com/309746/140232795-fe080bf1-d8d2-4b79-8f8a-b9df5795c903.png)

It is impossible to edit or delete the zombie entries; if you try, a toast popup in Visual Code appears saying that the extension responsible for the command had an error:

![image](https://user-images.githubusercontent.com/309746/140232839-b47ee517-88ea-49d2-b4bf-982a4648445d.png)

Thanks for taking a look!

**Comment by alefragnani** [comment] 2021-11-13 21:41
Hi @daniel347x ,

I didn't noticed this "zombie" behavior before, and had no success trying to reproduce. At first I thought it could be related to the _column position_ (the stored position to be larger than the actual line length), but no success either.

About the "missing bookmark icon in gutter", there is a recent issue #450, but I couldn't reproduce either. Before this reports, the only missing icon was from the Side Bar, which in the end appeared to be a VS Code issue (also reported in VS Code repo) which required a "force reinstall" (Uninstall Extension - Close VSCode - Open VSCode - Install Extension) in order to fix.

Just out of curiosity: 
* This error started to happen on recent releases, or are you starting to use the extension? 
* Which are your bookmarks settings?
* What happens if you run the `Bookmarks: List` command right after you open the folder with the "zombie bookmarks". Are you able to navigate to each bookmark, or does it display any error?

Thank you

**Comment by alefragnani** [comment] 2021-12-18 12:31
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2021-12-18 12:31 UTC
Labels: bug, need more info
