### ISSUE TITLE
it does not work in different workspaces/windows

### ISSUE THREAD

**Issue by GYHHY** [alefragnani/vscode-bookmarks#173] opened 2019-01-16 11:08 UTC
To be precise, my bookmarks in workspace A are not visible in workspace B.
I want to use the same bookmark data for all workspaces.
Can you add an option to the settings to enable it? I need it.

**Comment by alefragnani** [comment] 2019-01-16 17:26
Hi @GYHHY ,

The bookmarks are saved _per session_ for the project/folder that you are using. This means that what you are experiencing is the **expected behavior**. 

If you need to make the bookmarks _follow_ the folders, you must set `bookmarks.saveBookmarksInProject` to `true` in Workspace Settings, for the folders that you want this behavior, or in User Settings if you _always_ want this behavior. **But for now, multi-folders / workspaces are still not supported, so it may not _always_ work as expected for you.**

Hope this helps

**Comment by alefragnani** [comment] 2019-03-22 23:38
I’m closing this issue because its original request (support bookmarks between different workspaces) will not be developed, because the current behavior is the **expected** behavior.

The ability to have bookmarks _saved in project_ while opening multi-root/workspaces, will be tracked in #193 .

**Closed by alefragnani** 2019-03-22 23:38 UTC
Labels: enhancement, multi-root
