### ISSUE TITLE
Bookmark icons are missing

### ISSUE THREAD

**Issue by brentonhouse** [alefragnani/vscode-bookmarks#43] opened 2016-12-01 19:59 UTC
The bookmarks function properly but there is no indicator. Using version 1.7.2 on OS X.

**Comment by alefragnani** [comment] 2016-12-01 23:28
Hi @brentonhouse ,

It seems the same issue reported sometime ago (https://github.com/alefragnani/vscode-bookmarks/issues/34), caused by a bug in VSCode. It should be fixed now, at least in version 0.9.2 of the extension.

Are your extension updated?

**Comment by brentonhouse** [comment] 2016-12-01 23:34
I am running version 0.10 of plugin.

**Comment by alefragnani** [comment] 2016-12-01 23:37
Could you take a look at the *debug*? 

Open **Help / Toggle Developer Tools** and click in **Console** and check if there is any message about the extension. If you find, paste the message here.

**Comment by brentonhouse** [comment] 2016-12-03 01:28
no messages...

**Comment by alefragnani** [comment] 2016-12-03 01:47
In this case, I suggest you to reinstall the extension. Maybe something went wrong and the resources were not properly downloaded/installed.

But before that, you could _check_ the extension files. You just need to open the extensions folder (`Command Palette / Open Extensions Folder`), then navigate to `alefragnani.Bookmarks`. It should exists a folder called `images` and inside of it you should have a file called `bookmark.png`. This is the image to be displayed in the gutter.

Another thing that I remembered is about the **Themes**. Right at the beginning I noted a bug in _High Contrast _ thene. It was fixed in VSCode core. Are you using any custom Theme?

Hope this helps.

**Comment by alefragnani** [comment] 2016-12-14 23:20
Hi @brentonhouse , any news?

**Comment by brentonhouse** [comment] 2016-12-14 23:24
Tried uninstalling/reinstalling.  Also verified that the image exists in folder.  I am also not using high contrast theme.  No luck...

**Comment by brentonhouse** [comment] 2016-12-14 23:25
It was working for me a while back (before I opened ticket) but not since.

**Comment by alefragnani** [comment] 2016-12-14 23:46
I'm sorry about it. Unfortunately I don't have a Mac in hand to test (if this is OS related). I will try to get one from a friend and see if this happens there.

Let me know of any updates..

**Comment by alefragnani** [comment] 2017-05-21 01:20
Hi @brentonhouse , are you still experiencing this issue? If yes, just out of curiosity, are you using a Retina Mac?

I remembered your issue when looking for #70 . Maybe, if that is the case, could fix your issue too.

**Comment by alefragnani** [comment] 2017-05-24 00:25
Just released version 0.15.0 supporting SVG image as bookmarks. 
Could you check it?

**Comment by brentonhouse** [comment] 2017-05-24 04:15
I've uninstalled and reinstalled but keep getting 0.14.1.   I will try again tomorrow to see if it is cached somewhere.  Thanks!

**Comment by brentonhouse** [comment] 2017-05-24 14:32
Looks like 0.15.0 works!!! Thanks so much!!

**Closed** 2017-05-24 15:20 UTC
Labels: bug, help wanted
