### ISSUE TITLE
Glitch while switching the bookmarks

### ISSUE THREAD

**Issue by SachinMore** [alefragnani/vscode-bookmarks#364] opened 2020-12-18 11:09 UTC
Plugin is so much useful for bookmarking and switching between them,  however, I have been facing some trouble with the same now a days (it seems after update this happened).

Looks like while doing the NEXT (Ctrl+Alt+L), it is appending period (dot) in the text. PFA image FYR.

![dot_issue](https://user-images.githubusercontent.com/15128443/102608120-6228e080-414f-11eb-8001-a33dc7a09b1d.jpg)

Kindly see for the fix. Thanks!

**Comment by alefragnani** [comment] 2020-12-18 12:38
Hi @SachinMore ,

It appears you are experiencing the issue #240, #278, which in the end, is caused by VS Code itself.

Try reassigning the command for other keyboard shortcut, and it would be good to go.

Hope this helps

**Comment by alefragnani** [comment] 2021-01-10 15:56
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Closed by alefragnani** 2021-01-10 15:56 UTC
Labels: bug, caused by vscode, duplicate
