### ISSUE TITLE
bookmark by find

### ISSUE THREAD

**Issue by luca1010** [alefragnani/vscode-bookmarks#75] opened 2017-06-23 11:05 UTC
Hi,

It would be great to be able to set bookmark on lines that match a search (like Notepad++)

**Comment by alefragnani** [comment] 2017-06-25 21:15
Hi @luca1010 ,

Do you mean something like #7? Or using the _Find_ command (find in current file) 

Unfortunately, in both cases, there is no API yet 😢 . But when released, that's something I would like to add to the extension.

Hope this help

**Comment by luca1010** [comment] 2017-06-26 13:24
Hi, Yes, like #7

Grazie mille e buon lavoro.

Luca

**Comment by alefragnani** [comment] 2017-06-26 21:20
Closing as duplicate of #7

**Closed by alefragnani** 2017-06-26 21:20 UTC
Labels: duplicate, enhancement
