### ISSUE TITLE
Problem with polish character

### ISSUE THREAD

**Issue by paulhendrix** [alefragnani/vscode-bookmarks#28] opened 2016-07-15 08:21 UTC
VSCode Version: 1.3.1
OS Version: WIndows 10 (polish language)
Bookmarks: 0.9.0
Steps to Reproduce:

Press key RightAlt-l
Instead of getting polish character "Ł" some other operation is done (cursor is going to 1 col)

**Comment by alefragnani** [comment] 2016-07-16 23:35
Hi @paulhendrix ,

The line where the cursor goes, does it have a _bookmark_? 

If yes, you can remap the Shortcuts, because the extension uses `Ctrl + Alt`, which unfortunatelly is equals to `AltGr`, and can cause conflict with non-US Keyboard Layouts.

Hope this helps

**Comment by paulhendrix** [comment] 2016-07-18 10:44
Hi, thanks for the info.
This line doesnt have a bookmark.
I remaped this shortcut, 
thanks for help!

**Comment by alefragnani** [comment] 2016-07-21 04:05
Did it work after remapping? Because if there was no bookmark in the line/file, the cursor should not move.

If yes, could you give more details on how could I reproduce the issue?

Thanks

**Comment by alefragnani** [comment] 2016-07-21 04:06
https://github.com/Microsoft/vscode/issues/9205

**Comment by paulhendrix** [comment] 2016-07-21 07:36
I modified file keybindigns.json, added "ctrl+alt+l" shortcut:

// Place your key bindings in this file to overwrite the defaults
[
    { "key": "ctrl+F2",            "command": "bookmarks.toggle",
                                     "when": "editorTextFocus" },
{ "key": "F2",            "command": "bookmarks.jumpToNext",
                                     "when": "editorTextFocus" },
{ "key": "F2",            "command": "bookmarks.jumpToPrevious",
                                     "when": "editorTextFocus" },                                   
{
    "key": "ctrl+alt+l"    
}]

After that my polish letter "ł" works fine and bookmars also works ok
I think that the extension should not map ctrl+alt+l because it causes problems with international characters

**Comment by alefragnani** [comment] 2016-07-22 16:49
Duplicate of #13

**Closed by alefragnani** 2016-07-22 16:49 UTC
Labels: bug, duplicate
