### ISSUE TITLE
existing bookmark's line number should change as new lines added/deleted

### ISSUE THREAD

**Issue by ferencdg** [alefragnani/vscode-bookmarks#362] opened 2020-12-15 14:56 UTC
Hi,

thanks for the extension. Let's say I put a bookmark on line 100 and currently the text on that line is 'void function();', and new lines added/removed and that specific line's value didn't change. Could the line number change for the existing bookmark too? Right now I keep have to redo my bookmarks as I am editing the file, even though content of the line didn't change, just new lines added/removed.

thanks

**Comment by alefragnani** [comment] 2020-12-22 11:04
Hi @ferencdg ,

The extension does that. It's what I call _sticky_ behaviour. But there are some cases where it is not working perfectly yet ands still needs some work, like:

* Undo operations
* Formatters, like Prettier 

In both cases, there are open issues like #116, #168 and #118.

Hope this helps

**Comment by ferencdg** [comment] 2020-12-22 12:12
somehow from VS code extension panel when I install Bookmarks I can only install version 11.4, but github says 12.0 is already out... is this feature also in 11.4? 

maybe this feature doesn't work for me in 11.4 because of some plugin conflicts(I am using D language btw, but even with C++ it didn't work for me)

**Comment by alefragnani** [comment] 2020-12-22 22:12
No, it works this way a long time ago.

I'm not sure if the D or C++ extensions you use has auto-format or something like that. If yes, it must be the reason.

Version 12.0 was released almost a month ago, in Nov 24th. Version 11.4 a month earlier in Oct, 16th. Maybe the marketplace service was off/unstable when you tried to install/update, because right now, it returns 12.0 inside VS Code and on Marketplace https://marketplace.visualstudio.com/items?itemName=alefragnani.Bookmarks.

**Comment by trevyn** [comment] 2021-01-04 12:30
Another option is recognizing the content of the line, like this extension: https://marketplace.visualstudio.com/items?itemName=tintinweb.vscode-inline-bookmarks

The downside of that extension is that you need to add specific marks in your file content.

Perhaps some sort of hybrid would be best...

**Comment by alefragnani** [comment] 2021-01-05 11:56
Hi @trevyn ,

That's a totally different approach. In this case, the extension don't need to _keep track of file changes_ but instead just rerun the parser (which locates the `tags`), when changes are made. 

Here, on the other hand, there is nothing to parse. The bookmarks needs to be updated, based on the changes VS Code publishes.

**Comment by alefragnani** [comment] 2021-02-12 23:56
Closing as duplicate of #116, #118, #168

**Closed by alefragnani** 2021-02-12 23:56 UTC
Labels: bug, duplicate, need more info
