### ISSUE TITLE
Sidebar icon dissappears

### ISSUE THREAD

**Issue by it-sha** [alefragnani/vscode-bookmarks#272] opened 2020-02-25 09:57 UTC
After the last plugin update, this icon is not shown.
![image](https://user-images.githubusercontent.com/54891989/75236004-d6ac2080-57c5-11ea-867f-6573bdf37e3a.png)

![image](https://user-images.githubusercontent.com/54891989/75236103-f80d0c80-57c5-11ea-9d39-726b98939c6e.png)

Bookmarks version 11.0.0

**Comment by alefragnani** [comment] 2020-02-25 22:33
Hi @it-sha ,

It appears a duplicate of #160 .

I have experienced that too sometimes, but not only on my extension, but on Docker, GitLens and PowerShell as well. It seems to be an issue caused by VS Code, not the extension itself. In my case, most of the times the error goes away when I restart VS Code (Close and Open Again). But I remember at least once, I have to uninstall and reinstall the extension

Hope this helps

**Closed by alefragnani** 2020-02-25 22:33 UTC

**Comment by it-sha** [comment] 2020-02-26 08:49
Hi @alefragnani. Thank you for the quick answer.

Probably this was fixed by new VSCode updates. After the VSCode reloading problem not present.

**Comment by davidbarredo** [comment] 2020-04-21 12:44
I have a similar problem after accidentally moved the sidebar panel to the "terminal" panel.

The sidebar for bookmarks is no longer working, and it appears as "Explorer"
![image](https://user-images.githubusercontent.com/657206/79867193-3ac21e00-83de-11ea-8174-f6af30d060ce.png)

I´ve tried to uninstall and install again the extension but it's not working.

![image](https://user-images.githubusercontent.com/657206/79867381-8ecd0280-83de-11ea-9aef-036df3e5df9b.png)

**Comment by alefragnani** [comment] 2020-04-21 13:21
Hi @davidbarredo ,

I had found it myself right after installing VS Code 1.44, and noted that this is related on VS Code itself, not the extension.

I posted this issue (https://github.com/microsoft/vscode/issues/94733) on VS Code repo, and the VS Code team labeled as _as designed_  as you can see in [their comment](https://github.com/microsoft/vscode/issues/94733#issuecomment-611556173) 😕.

As I discovered myself, you can _reset_ the Side Bar to its original state using the `View: Reset View Locations` command, but it sill reset _any customization you did_.

Hope this helps

**Comment by davidbarredo** [comment] 2020-04-21 13:59
Thanks! It worked, but now I need to customize somethings again ;-)
