### ISSUE TITLE
[BUG] - Bookmark groups can be opened by a single or double click depending on VS Code setting

### ISSUE THREAD

**Issue by tonghoangvu** [alefragnani/vscode-bookmarks#548] opened 2022-07-31 00:38 UTC
**Environment/version**

- Extension version: v13.3.1
- VSCode version: 1.69.2
- OS version: 21H2, build 22000.832

**Steps to reproduce**

1. To have some bookmarks
2. Display all bookmarks as a tree view
3. Open/close any bookmark group

Bookmark items can be opened with a single or double click depending on the VS Code `workbench.list.openMode` setting.

But group bookmarks are always opened with a single click. I feel a bit inconsistent, this behavior is not the same as in Files or Search. Better to use VS Code `workbench.tree.expandMode` setting.

![image](https://user-images.githubusercontent.com/64119341/182004522-f415e282-78c4-4b19-98f2-037bb888a1ee.png)

Thanks.

**Comment by alefragnani** [comment] 2022-07-31 19:15
Hi @tonghoangvu ,

It seems VS Code is not _respecting/reproducing_ such behavior to extensions, because in fact, VS Code does not provide any API for extensions to choose/override such behavior. Neither `List / Open Mode` nor `Tree / Expand Mode`. 

I'll double check this and if confirmed, open an issue to VS Code itself. Then, we will have to wait for VS Code team to provide API or fix VS Code itself

Hope this helps

**Comment by alefragnani** [comment] 2022-08-17 22:05
My assumptions were correct, and this is handled by VS Code. But, it is not being _applied_ to extensions today. 

I have asked in the discussions repo (https://github.com/microsoft/vscode-discussions/discussions/88) and the VS Code team confirmed the issue. They opened an issue (https://github.com/microsoft/vscode/issues/158159 and it should be fixed in the August release.

Worth mention however a comment from the VS Code team, which explains _how_ this works:

> `workbench.tree.expandMode ` is ignored in extension provided trees when the element that the user is clicking on has a `command` associated with it.

Once VS Code is updated, this issue should will be fixed, and the extension will respect the VS Code setting.

Hope this helps

**Closed by alefragnani** 2022-08-17 22:05 UTC
Labels: bug, need more info, caused by vscode
