### ISSUE TITLE
Make path of bookmarks.json crossplatform

### ISSUE THREAD

**Issue by fzzr-** [alefragnani/vscode-bookmarks#66] opened 2017-04-12 18:14 UTC
Currently the path of file looks like "for win only".

`.vscode\\bookmarks.json`

but should be

`.vscode\/bookmarks.json`

![vsc bookmarks fpath issue mov](https://cloud.githubusercontent.com/assets/888526/24972679/e9475d9a-1fc4-11e7-8424-105cca42c76e.gif)

**Comment by alefragnani** [comment] 2017-04-12 18:21
Duplicate of #65

**Closed by alefragnani** 2017-04-12 18:21 UTC
Labels: bug, duplicate
