### ISSUE TITLE
[BUG] - Explorer view doesn't work

### ISSUE THREAD

**Issue by gmccullo** [alefragnani/vscode-bookmarks#672] opened 2023-11-28 09:03 UTC
It's been a long time since I've seen the Bookmarks explorer work. It shows a count on the icon, but the explorer is empty except for the progress indicator which never stops.

**Environment/version**

- Extension version: 13.4.2
- VSCode version: 1.84.2
- OS version: win11

**Steps to reproduce**

1. add bookmarks
2. look at bookmarks explorer

**Comment by alefragnani** [comment] 2024-04-02 01:27
Hi @gmccullo ,

You are probably facing the same issue as #630 , as the badge currently displays the number of registered bookmarks, but should display the number of _valid_ bookmarks. 

Another issue is related to some untitled files or files outside of the current worspace like #328 and #397, which I'm planning to handle together.

I'm closing this issue as duplicate of those. 

Hope this helps

**Closed by alefragnani** 2024-04-02 01:27 UTC
Labels: bug, duplicate, side bar
