### ISSUE TITLE
It's alway hanging

### ISSUE THREAD

**Issue by cofei** [alefragnani/vscode-bookmarks#543] opened 2022-05-27 10:39 UTC
**Environment/version**

- Extension version: v13.3.0
- VSCode version: 1.67.2
- OS version: 10.0.19043

**Steps to reproduce**

1.  during debug, and open Bookmark
2.  clikc one file and choose one book mkar.
3. jump into the code.
4. remove this book mark and add another.
5. refresh Bookmark. it's hanging.

![image](https://user-images.githubusercontent.com/29910419/170684256-a1fd95a8-5ace-4331-b0e3-7e9267f32d25.png)

**Comment by alefragnani** [comment] 2022-07-13 03:16
Hi @cofei ,

I just tried to reproduce your steps, but didn't noticed the _hanging_ behavior. Could you please provide more details about the project you are debugging and the file which you added a Bookmark?

* Are you running locally or remotely?
* Is the bookmarked file contained in the project you have open, or is it some lib or external resource which your project is _importing_?
* What are you using to toggle on/off bookmarks; Are you using commands, context menu or this `Bookmarks: Toggle` button in the Side Bar?

I have already noticed this _hanging / infinite loop_ loading behavior, when the bookmarked file _was not found_. Specially for files outside the project or libs. If that's the case, maybe you are facing #307 or #397.

Hope this helps

**Comment by alefragnani** [comment] 2022-07-24 03:09
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2022-07-24 03:09 UTC
Labels: bug, need more info
