### ISSUE TITLE
Bookmarks not saved

### ISSUE THREAD

**Issue by Otiel** [alefragnani/vscode-bookmarks#99] opened 2018-03-27 13:28 UTC
I'm not sure if I'm using the extension as it is supposed to: I have a simple file (no folder/workspace opened) for which I set some bookmarked lines. After closing VS code and reopening the file, the bookmarks are gone.

Does the extension only save bookmarks for files inside a workspace?

**Comment by alefragnani** [comment] 2018-04-04 02:05
Hi @Otiel ,

First of all, sorry for taking so long to answer you. It's been a busy period and I'm not being able to give the proper attention to some projects.

About your issue, it _should_ work. No matter if you have a **Project**, a **Workspace** or **No Folder** (as in your case), it should be able to save/restore the bookmarks. But first, if you need this behavior, you must be sure to have set `bookmarks.saveBookmarksInProject` to `true` (it is `false` by default) on `File / Preferences / Settings`.

Hope this helps

**Comment by alefragnani** [comment] 2018-04-04 11:09
Ops, I messed the comments 😢 . 

The `bookmarks.saveBookmarksInProject` will not work for **No Folder** and **Workspace** scenarios, because in fact, there is no _project/base folder_ to store `.vscode\bookmarks.json` file. The _multi-root_ adoption was discussed in #82.

**Comment by Otiel** [comment] 2018-04-04 13:29
I see. I thought that you meant the user profile `.vscode` folder (`C:\Users\[user]\.vscode\` on Windows).

So if I understand correctly, there's no way to get the bookmarks saved for a **No Folder**, **No Workspace** file?

What happens when `bookmarks.saveBookmarksInProject` is set to `false`? Where are the bookmarks saved?

**Comment by alefragnani** [comment] 2018-04-04 15:40
> So if I understand correctly, there's no way to get the bookmarks saved for a No Folder, No Workspace file?

For **Workspace/Multi-root** scenario, not yet. I need to refactor how bookmarks are stored to be able to have this (probably having a `.vscode\bookmarks` for each folder in the workspace). 

For **No Folder** scenario, it will never happen, because _there is not root folder_ to store, so it will always be stored in VS Code internals.

> What happens when bookmarks.saveBookmarksInProject is set to false? Where are the bookmarks saved?

It is stored in VS Code internals, which is a `Local Storage` (from Chromium). You could see it in `Toggle Developer Tools \ Application \ Local Storage \ file://` and filter by `alefragnani.bookmarks`. Each project/workspace that you opened will be there, with its bookmarks.

Hope this helps

**Comment by Otiel** [comment] 2018-04-04 16:27
I'm not sure I follow you.

>For No Folder scenario, it will never happen, because there is not root folder to store, so it will always be stored in VS Code internals.

So if I'm using `bookmarks.saveBookmarksInProject` set to `false`, the bookmarks should be stored in the Local Storage, thus they should be remembered even for alone files?

**Comment by alefragnani** [comment] 2018-04-04 16:56
Exactly 😄

**Comment by Otiel** [comment] 2018-04-04 17:40
Alright, thanks for the confirmation. 😃 

So in that case, this bookmark one line 1 should be displayed, correct? 😊

![image](https://user-images.githubusercontent.com/3851902/38324200-dc886678-383f-11e8-9323-942fff7331e0.png)

**Comment by alefragnani** [comment] 2018-04-22 00:58
Hi @Otiel ,

Sorry for the silence. I was a bit busy and totally forgot to answer you. Really sorry.

Yes, that `json` entry means that it _should_ have a bookmark in line 1. I will take a look at it

Thanks

**Comment by harleyguru** [comment] 2018-05-28 18:16
when I save the file (I've set editor formatting on save) after I set bookmark and edit file, its cleared. any reason?

**Comment by robertmirro** [comment] 2018-12-11 19:53
@harleyguru I recently switched from windows to mac and am seeing this behavior as well when saving files (bookmarks disappear after save even if line numbers don't change).  It used to work for windows, but I no longer have that laptop to test again for sure.

**Comment by alefragnani** [comment] 2018-12-11 21:38
If you are losing your bookmarks “after saving” and have `formatOnSave` turned on, or if you use a formatter like Prettier, you may be facing the same issue as #118 .

**Comment by robertmirro** [comment] 2018-12-11 22:00
Thanks for the prompt response!  Before I posted I verified that `editor.formatOnSave` was not on and also that Prettier is not used for this project.  I also disabled some other vscode plugins just to be sure they're not interfering. 

I just turned off `eslint.autoFixOnSave` and the bookmarks no longer disappear on save.

The vscode user settings I'm using on this mac were taken from the windows laptop, so I guess *something* is mac specific.

**Comment by alefragnani** [comment] 2018-12-11 22:08
Really weird, unless you don’t have eslint installed/active on that Windows machine.

Unfortunately I don’t have a Mac anymore to test, but I guess that based on its similarities with `formatOnSave` settings, the root cause should be the same in both cases. I’ll probably have to chat with VSCode team to see how to deal with it, because some API is needed.

Thanks you for your feedback 👍

**Comment by robertmirro** [comment] 2018-12-11 22:20
This project uses eslint so it was installed on windows as both a vscode plugin and as dependency via package.json.

I've noticed other format-on-save weirdness on this mac that seems to be related to eslint, so maybe that is the culprit.

I use the vscode Sync Settings plugin to produce identical settings in windows vs mac and verified they were the same (including plugin versions and npm package versions) before I turned the windows laptop back into IT, so I'm at a loss...

Anyway, thanks again!

**Comment by harleyguru** [comment] 2018-12-12 02:09
@robertmirro yeah I am always using macOS.
Have you found out the solution for this issue?

**Comment by alefragnani** [comment] 2018-12-12 10:00
@harleyguru no, I didn't find a solution yet, because in fact, maybe there isn't 😢 

If the problem is really created by these _formatters/format_on_save events_, I would need a new VS Code API that could tell me how the lines moved, to be able to _update_ the bookmarks. What I'm seeying as  a _potential workaround_ is to turn off the _sticky behavior_, so it wouldn't update the bookmarks position when you change the text. That's the proposal for #118 .

Unfortunately, I don't have a MacOS available, so if the issue happens only on MacOS, I have no way to fix it.

**Comment by robertcatgithub** [comment] 2018-12-31 02:47
Alessandro 
OK I need to move a project folder which has bookmarks. 
My search to ensure the bookmarks are retained led to this thread.
So I followed your 1st response and set `saveBookmarksInProject` to `true`.

I came back to Code, and to my dismay, [Bookmarks: Explorer is now empty!](https://media.tenor.com/images/276eb7185f4f8a167cd1be58f6a1ff53/tenor.gif) 
and .vscode folder does not have any bookmarks info.
.vscode/bookmarks.json only showed up when I added a bookmark for test.

So in [your next comment](https://github.com/alefragnani/vscode-bookmarks/issues/99#issuecomment-378646184) you revealed where the bookmarks info are stored, and I found the data.

What can I do now ?  Is there a way to convert that string to json to paste into bookmarks.json

thanks

**Comment by alefragnani** [comment] 2022-08-02 00:43
I'm closing this issue because no new comments/reports has been added for around 4 years. 

I couldn’t reproduce the original issue (bookmarks not saved), and since then, the multi-root support was added and improved, and now the extension can load the _local/inProject_ bookmarks while using Workspaces. I guess the issue may now be solved.

The other _formatter/prettier/eslint_ issue should be fixed with the new Sticky engine released in #463. And the bookmarks are now properly moved to _local/inProject_ when you update the `saveBookmarksInProject` setting in #242 .

Feel free to open a new issue if the error returns

Thanks for your understanding

**Closed by alefragnani** 2022-08-02 00:43 UTC
Labels: bug, sticky
