### ISSUE TITLE
[FEATURE] - Support insert or sort of Explorer Sidebar

### ISSUE THREAD

**Issue by YIGAOYI** [alefragnani/vscode-bookmarks#676] opened 2023-12-05 07:37 UTC
Great extension. Would love to see the ability to support insert or sort of explorer sidebar

**Comment by henan-lujun** [comment] 2024-02-03 01:30
It's very nice to support sort the bookmarks by label's name/title.

**Comment by alefragnani** [comment] 2024-04-02 22:48
Hi @YIGAOYI ,

First of all, I'm glad to know you like the extension.

About your request, I'm not sure I understand what you mean about _support insert or sort of explorer sidebar_. 

Sorting is already being tracked in #217 and #443, and adding bookmarks via Side Bar is being tracked in #238.

If these issues corresponds to your requests, I think this one could be closed as duplicates, right?

Hope this helps

**Comment by alefragnani** [comment] 2024-04-16 00:03
I'm closing this issue because no new comments has been added since my last question, and the requests seems to be duplicate of already existing ones.
Feel free to reopen/comment if they are not duplicates, providing more details.

Thanks for your understanding

**Closed by alefragnani** 2024-04-16 00:03 UTC
Labels: duplicate, enhancement, need more info
