### ISSUE TITLE
Error when edit label by shortcut

### ISSUE THREAD

**Issue by tonimarquez84** [alefragnani/vscode-bookmarks#214] opened 2019-05-31 12:05 UTC
Can't edit a bookmark label by shortcut:
> Running the contributed command: 'bookmarks.editLabel' failed.

**Comment by alefragnani** [comment] 2019-06-05 10:50
Hi @tonimarquez84 ,

Could you share more information about this error, so I could try to reproduce the error?

* Are the other extension's commands also failing?
* Which VS Code version _and_ release are you using?
* How many bookmarks did you have in the file
* How many files did you have in your workspace/folder
* Which is the size of the file that you are trying to edit the label (Mb, LOC)
* A print/video demonstrating the issue would help
* Open `Toggle Developer Tools / Console` and paste the any error message here.

Thank you

**Comment by tonimarquez84** [comment] 2019-06-05 13:01
Of course:

- Are the other extension's commands also failing?
No, I have the issue with this command (`bookmarks.editLabel`).

- Which VS Code version and release are you using?
VS Code v1.34.0 (1.34.0).

- How many bookmarks did you have in the file?
Whatever you have the issue is happening the same way.

- How many files did you have in your workspace/folder?
Is a big project with at least 300 files or more (including binaries).

- Which is the size of the file that you are trying to edit the label (Mb, LOC)?
Is happening in all files (a lot of different sizes).

- A print/video demonstrating the issue would help.
![snapshot](https://user-images.githubusercontent.com/7965563/58958209-b1dccc80-87a2-11e9-8c61-81d18ffc8e9e.png)

- Open Toggle Developer Tools / Console and paste the any error message here.
Nothing appears in the Console, but yes in a small warning message in the bottom-right corner notification bar saying: `Running the contributed command: 'bookmarks.editLabel' failed.`

**Comment by alefragnani** [comment] 2019-06-05 15:14
The `Edit Label` command only exists in the **Side Bar**, so I suppose you did _hide it_, before print screen, right? 

Also, could you say if the bookmark itself (presented in the Side Bar) is correct? I mean, does it refers to a valid column/line? I'm thinking that maybe an error in the bookmark itself may be responsible for it.

Hope this helps

**Comment by tonimarquez84** [comment] 2019-06-06 10:55
Is happening also with the sidebar opened. If i do a second click over the bookmark in the sidebar is showing same error.

![snapshot](https://user-images.githubusercontent.com/7965563/59027853-64239b00-885a-11e9-8234-602463758529.png)

**Comment by alefragnani** [comment] 2020-03-13 02:25
Hi @tonimarquez84 ,

Are you still facing this issue? Personally, I didn't reproduced nor experienced this, and no other user has commented yet, fortunately or unfortunately 😕 .

Please, let me know any news about it

**Comment by alefragnani** [comment] 2020-04-11 01:22
I'm closing this issue because no new comments has been made since my last question. 
Feel free to reopen/comment if the error still occurs.

**Closed by alefragnani** 2020-04-11 01:22 UTC
Labels: bug, need more info

**Comment by moritzPlossSymphony** [comment] 2020-06-03 15:40
For what it's worth, I have the exact same issue as @tonimarquez84 with VS Code 1.45.1 and Bookmarks 11.2.0 on macOS. I tried to assign the command to different shortcuts, but it always results in the same error as described above.

**Comment by alefragnani** [comment] 2020-06-04 10:28
Hi @moritzPlossSymphony ,

Looking closer to your report and returning to @tonimarquez84 description, I think I finally was able to reproduce the error. 

It appears you _defined a keyboard shortcut_ to the command, and tried to use it not in the Side Bar itself, but using the keyboard shortcut, right?

If that’s the case, then you are using an unsupported scenario. That `Edit Label` command is supposed to be used only in the Side Bar, not outside. That’s one of the reasons it’s not available in the `Command Palette`. The same happens for the `Clear` and `Delete` commands in the Side Bar. These commands should not be available in the `Keyboard Shortcuts` preferences. I think I’ll have to check on VS Code repo about that.

If you want update the bookmark’s label, via Keyboard Shortcuts, you should use the `Bookmarks: Toggle Labeled` command. It will open the same input for you to define/update the label assigned to the Bookmark in the current line.

Hope this helps
