### ISSUE TITLE
[BUG] - prettier formatters after

### ISSUE THREAD

**Issue by ozknkrkc** [alefragnani/vscode-bookmarks#497] opened 2021-12-09 12:22 UTC
All of the places we marked after the format with prettier are shifting and it would be much better if a filtering system was added as in the todo plugin.

**Comment by alefragnani** [comment] 2021-12-10 15:42
Hi @ozknkrkc ,

What do you mean by that? Could you please provide more details (step by step/image/video)?

In recent releases, the Bookmarks extension started to understand/recognize formatters (not specifically Prettier or any other). It was working just fine until a month ago, which may be something with VS Code or Prettier itself, because nothing has changed in Bookmarks. 

Is your scenario similar to #486 ? If not, please provide more details.

Hope this helps

**Comment by alefragnani** [comment] 2021-12-10 15:52
Sorry about the issue reference, but looking again, that case is an _expected behavior_ (bookmarks on removed lines, are removed as well).

So please, provide details about your scenario.

**Comment by alefragnani** [comment] 2021-12-18 12:29
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2021-12-18 12:29 UTC
Labels: question, sticky, need more info
