### ISSUE TITLE
[BUG] - Bookmarks don't appear for global VSCode settings.json in the bookmarks explorer.

### ISSUE THREAD

**Issue by futuremotiondev** [alefragnani/vscode-bookmarks#700] opened 2024-03-07 10:23 UTC
**Environment/version**

- Extension version: v13.4.2
- VSCode version: v1.87.0
- OS version: Windows 10 Pro x64 22H2

**Steps to reproduce**

1. Open your global VSCode `settings.json`
2. Add some labeled bookmarks
3. Open the bookmarks viewer
4. Expand the `settings.json` entry
5. No bookmarks are shown despite the fact they exist in the file

![Code_nojKU60XNr](https://github.com/alefragnani/vscode-bookmarks/assets/33441569/d719ccb4-5621-440d-a822-effb3c80e332)

**Comment by alefragnani** [comment] 2024-04-03 00:06
Hi @futuremotiondev ,

Could you describe the _folder/workspace_ you have opened, prior to the User Settings? Is it located in the `C:` drive, or is it the `D:\Dev` which appears in the terminal?

I'm asking because I tried to reproduce the error, using a folder located in the same `C:` drive, and had no issues. On the other hand, opening a folder on another drive (using `subst`), the error occurred.

If that's your scenario, you are facing the same issue reported in #397.

Hope this helps

**Comment by alefragnani** [comment] 2024-04-27 21:20
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2024-04-27 21:20 UTC
Labels: bug, duplicate, need more info, schemes
