### ISSUE TITLE
Bookmarks: Explorer not working

### ISSUE THREAD

**Issue by turijs** [alefragnani/vscode-bookmarks#127] opened 2018-07-16 14:53 UTC
I just installed the plugin today and the bookmarks explorer appears to be caught in an infinite loop of refreshing - I see no bookmarks (even though I have added some) and the little blue line keeps animating across the top. I tried reloading the plugin and restarting vscode, but nothing seems to make a difference.
See the attached screenshot for errors I saw in the dev tools.
I also tried to disable the explorer with the setting `"bookmarks.treeview.visible": false` but this had no effect.
I am running:
- vscode-bookmarks 9.0.0
- vscode 1.25.1
- Ubuntu 16.04
![vscode-bookmarks-errors](https://user-images.githubusercontent.com/17010148/42765579-589ffc52-88e6-11e8-8c5d-92aef947b7fb.png)

**Comment by alefragnani** [comment] 2018-07-16 15:48
HI @turijs ,

I'm sorry to hear that 😢 

I saw a similar message appears when I was developing the new version, while switching between the _new_ and _old_ extension versions in the same folder/workspace, but not after using exclusively the new version. It happened because the JSON structure that stores the bookmarks has changed to suport line/column/label, and some parts in the extension weren't still updated to correctly use it. It _should_ be fixed now, but appears not ...

If you could paste the `bookmarks.json` content here, I could take a look to identify what's wrong, and release a bugfix. To do this, you should use the `Developer Tools`, goes to `Application`, `Local Storage` and then `file://` and search for `alefragnani.bookmarks` for the folder/workspace that raises the error.

About the _animation_, I have no idea. Maybe an _infinite loop_ caused by that error is the reason.

If you can't get the `bookmarks.json` for any reason, or if you don't care about losing the bookmarks for that folder/workspace, you could simply clear them, using the `Bookmarks: Clear from All Files` commands. It should _reset_ the bookmarks and let you work as before.

Hope this helps

**Comment by simkessy** [comment] 2018-07-19 02:21
I'm having the same issue mentioned about.

**Comment by Rusenec** [comment] 2018-07-19 07:12
I have the same issue. Since the last update of VSC bookmarks disappeared from the explorer view. There is no way to toggle it on/off as it was before, as well. Deleted bookmarks.json, reinstalled - same. Any way to fix it?

**Comment by crystalfp** [comment] 2018-07-20 12:33
Same error as @turijs in the console:

```
/C:/Program Files/Microsoft VS Code/resources/app/out/vs/workbench/workbench.main.js:1376   ERR Cannot read property 'line' of undefined: TypeError: Cannot read property 'line' of undefined
	at Promise.all.then (C:\Users\Mario Valle\.vscode\extensions\alefragnani.bookmarks-9.0.0\out\src\BookmarkProvider.js:182:60)
	at <anonymous>
```

**Comment by alefragnani** [comment] 2018-07-21 12:52
Hi @Rusenec ,

The **Bookmarks** _are not_ in the **Explorer** view anymore. It received its own **Activity Bar**.

https://github.com/alefragnani/vscode-bookmarks/blob/master/images/bookmarks-activity-bar.gif
![image](https://user-images.githubusercontent.com/3781424/43035772-95ee25be-8ccb-11e8-9042-e1cac0004324.png)

**Comment by zmijat** [comment] 2018-07-21 14:44
Same issue here.

I'm using single folder, and have overriden the following bookmark settings in User Settings:

- "bookmarks.saveBookmarksInProject": true
- "bookmarks.navigateThroughAllFiles": true

I've cleared all the bookmarks (confirmed .vscode/bookmarks.json removed), hide bookmarks view from the side bar and restarted vscode. Placing a new bookmark in one file worked (displayed in Bookmarks view). Placing bookmark in another file triggered infinite loop. Note that I was able to jump between bookmarks using shortcuts, even if the second bookmark was not displayed in Bookmarks view.

After another vscode restart (without clearing bookmarks), entering the bookmarks view triggers infinite loop immediatelly (and no bookmarks visible in view). Still able to jump between bookmarks using shortcuts.

**Comment by Rusenec** [comment] 2018-07-21 16:46
Thank you @alefragnani.
Hadn't noticed that, I hide the activity bar, but I guess will have to use the extension from there.

**Comment by alefragnani** [comment] 2018-07-24 01:30
I finally could reproduce the error. 

I'll do some more tests to be sure. Let's hope this is the only one, so a fix should be released soon.

Thanks for your patience.

**Closed** 2018-07-25 01:52 UTC
Labels: bug

**Comment by crystalfp** [comment] 2018-07-25 07:35
It works! Thanks for your work. mario
