### ISSUE TITLE
[BUG] - bookmarks.json file dissapeared shortly after enabling bookmarks.saveBookmarksInProject

### ISSUE THREAD

**Issue by vbrozik** [alefragnani/vscode-bookmarks#618] opened 2023-06-22 09:19 UTC
I am normally using VS Code preview but I needed to use the normal release. I noticed that I do not see my bookmarks in my normal release. So I did  the following:
* in the preview version I enabled `bookmarks.saveBookmarksInProject`
* noticed that `.vscode/bookmarks.json` was created
* closed VS Code preview
* started VS Code normal release
* noticed that there are no bookmarks and no `.vscode/bookmarks.json` file

**Environment/version**

- Extension version: Name: 13.3.1
- VSCode version: 1.79.2, 1.80.0-insider (Commit: e8b22318bfab2e52d5dbceee767e8b4bfe9b5300, Date: 2023-06-22T05:34:30.725Z)
- OS version: Windows 10 21H2, WSL2 With Ubuntu 22.04

**Steps to reproduce**

1. enable `bookmarks.saveBookmarksInProject` in VS Code preview (setting synchronization is on)
2. close VS Code preview
3. start VS Code normal release
4. the file `.vscode/bookmarks.json` is gone and all bookmarks are lost

**Comment by alefragnani** [comment] 2023-06-22 22:26
Hi @vbrozik ,

AFAIK, settings sync does not work between different releases, which means that the setting you defined in Insiders won’t be available in Stable and vice versa. The expected behavior in this case would be Stable release simply _ignore_ the bookmarks from `.vscode/bookmarks.json` file, but not delete the file. In order to delete the `.vscode/bookmarks.json` file, two things must happen:

* The setting must be defined to save bookmarks in project
* There is no bookmark in the folder

But even if you change the setting from true to false, the `.vscode/bookmarks.json` won’t be deleted.

If you need the bookmarks to be _portable_, no matter which VS Code release you are using, you should define the `saveBookmarksInProject` setting _in the folder_. Doing so, VS Code will save a `.vscode/settings.json` file within the project/folder and whenever you open that folder, those settings will be loaded and used.

Hope this helps.

**Comment by alefragnani** [comment] 2023-07-14 22:41
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2023-07-14 22:41 UTC
Labels: bug, need more info
