### ISSUE TITLE
Cannot add bookmark to file over 50MB

### ISSUE THREAD

**Issue by kkwan-git** [alefragnani/vscode-bookmarks#299] opened 2020-05-14 20:44 UTC
Issue Type: <b>Bug</b>

Pressing ctrl-alt-k in a file over 50MB results in message window "(i) Open a file first to toggle bookmarks

Extension version: 11.2.0
VS Code version: Code 1.45.1 (5763d909d5f12fe19f215cbfdd29a91c0fa9208a, 2020-05-14T08:27:35.169Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i7-7820HQ CPU @ 2.90GHz (8 x 2904)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off_ok<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off_ok<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|31.81GB (17.32GB free)|
|Process Argv|C:\_\tmp\MotionTrace.csv|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by alefragnani** [comment] 2020-05-14 20:55
Hi @kkwan-git ,

I'm sorry to say, but that's caused by a VS Code limitation, which does not allow the extensions to "read" large files.

Duplicate of #31

**Closed by alefragnani** 2020-05-14 20:55 UTC
