### ISSUE TITLE
[BUG] - Bookmark for the same file stored more than once

### ISSUE THREAD

**Issue by marmidr** [alefragnani/vscode-bookmarks#416] opened 2021-03-18 07:51 UTC
**Environment/version**

- Extension version: v13.0.4
- VSCode version: 1.54.3
- OS version: OS | Linux x64 4.4.0-19041-Microsoft, Remote | WSL: Ubuntu

Hi,
VSCode has a little issue - files are opened with relative or absolute path, especially when navigating through the code.
I noticed that my bookmarks disappeared, but later realized that on sidebar the same file is listed twice, like so:
1st: `/home/user/Proj/src/parser.cpp`
2nd: `../src/parser.cpp`

Maybe convert path from Code to its absolute form before storing? Just imagine what happened, when I created symbolic link to project directory and used it to open project. Even more weird path cases :)

**Comment by alefragnani** [comment] 2021-03-20 16:09
Hi @marmidr ,

As you noticed, this is a VS Code behavior. Prior to the latest release of the extension (v13), I would say this workaround could be easily added, but I don’t see this happening so easily anymore. To be able to support **Remotes**, I had to use **relative paths**, because depending on how you opened the folder (locally or remotely), the `root folder` changes. So I combine both to identify the files

 I’ll take a closer look if something can be done, but supporting **Remotes** is the priority .

Hope this helps

**Comment by marmidr** [comment] 2021-03-22 11:50
Thanks for the answer. 
Obviously, something trivial from user perspective may be complex from developer PoV.
Thanks for your job ;)

**Comment by alefragnani** [comment] 2022-05-03 00:04
I’m closing this issue because it is caused by how VS Code works, with no feasible workaround. 

But, maybe using a _global storage_ as requested in #287 this could be achieved, because in the end, the bookmark will be _relative to a file in the file system_, not _in the opened workspace_.

Thanks for your understanding.

**Closed by alefragnani** 2022-05-03 00:04 UTC
Labels: bug, caused by vscode
