### ISSUE TITLE
Not working properly - no bookmark icon, no bookmarks sidebar

### ISSUE THREAD

**Issue by stellarwebworks** [alefragnani/vscode-bookmarks#450] opened 2021-07-07 23:26 UTC
### Discussed in https://github.com/alefragnani/vscode-bookmarks/discussions/449

<div type='discussions-op-text'>

<sup>Originally posted by **stellarwebworks** July  8, 2021</sup>
I installed the bookmarks plugin (version 13.1.0) in latest version of Visual Studio Code (1.57.1) but it does not seem to be working properly. When I bookmark a line I expect to see a bookmark icon in the gutter but there is none. Also there is no sidebar as shown in the instructions.
It does work partially in that the bookmarks seem to be created and I can see a little blue mark in the scrollbar which I can click on and it takes me to the line that I bookmarked. I tried uninstalling, restarting VS Code and reinstalling but did not help. Please advise.</div>

**Comment by stellarwebworks** [comment] 2021-07-08 03:51
actually just realised that the bookmarks sidebar is there but there is no icon so I didn't see it. This is what it looks like in my view:
![image](https://user-images.githubusercontent.com/16406746/124859586-4eb66780-e004-11eb-928e-ccfe37d8ae3f.png)

**Comment by stellarwebworks** [comment] 2021-07-08 03:52
actually just realised that the bookmarks sidebar is there but there is no icon so I didn't see it. This is what it looks like in my view:
![image](https://user-images.githubusercontent.com/16406746/124859673-70afea00-e004-11eb-83db-609112e9f480.png)

**Comment by stellarwebworks** [comment] 2021-07-13 03:19
Any fixes or suggestions for this issue? Btw. I've checked if it is related to theme but same issue no matter which colour theme I select.

**Comment by fade2gray** [comment] 2021-07-13 16:50
Have you looked at issue #397 ?

**Comment by stellarwebworks** [comment] 2021-07-13 21:27
I looked at it now but I don't think it's related to my issue. In my case the problem is that the icons are not showing (bookmark icon in gutter and icon on bookmarks tab in sidebar. I've tried uninstall and reinstall the plugin to no avail.

**Comment by stellarwebworks** [comment] 2021-07-13 21:45
I found a workaround for the missing bookmark icon in gutter. In the extension settings there is a setting for Gutter Icon Path, so I downloaded a bookmark icon and inserted the path to it and that works. The icon on bookmarks tab is still missing but that's not as big an issue once I know the tab is there.

**Comment by alefragnani** [comment] 2021-07-14 23:59
Hi @stellarwebworks ,

I have seen the _missing Side Bar icon_ a few times, and up until now, it has always been caused by some issue in the installation process (which is managed by VSCode). It happened not only on this extension, but from other developers too. BTW, I guess two releases ago this was happening a lot for extension developers, while debugging the extensions.

To fix this installation issue, you must reinstall the extension. But you must do a _full reinstall_, which means:

* Go to the Extensions view
* Select the extension
* Click `Uninstall`
* Instead of _reloading_ the window as prompted, you must **Close all VS Code windows**. This will make sure the older installation is fully removed from VS Code internals, once you open VS Code again.
* Open VS Code again
* Go to the Extensions view
* Install the extension again

Please, try these steps to see if it fixes the missing resources.

Hope this helps

**Comment by stellarwebworks** [comment] 2021-07-28 22:04
Hi Alessandro,
I tried that, following the steps exactly but it did not bring in the icons. I thought the settings would be reset on the reinstall but there weren't - the Gutter Icon Path was still set with the alternative bookmark icon that I had added. But in any case, by virtue of that particular setting, it is perfectly usable for me as it is. Only thing missing is the tab icon, and now that I know where the tab is located, it is no big deal. Thanks for your help and for the plugin!
Aidan

**Comment by schittli** [comment] 2021-08-06 09:11
Hello @stellarwebworks 

### I have the same issue as described here, but it's only a VSCode gutter redraw issue:

1. I set the Bookmark on line 10, but afterwards, the icon is not displayed:
![image](https://user-images.githubusercontent.com/8282673/128486559-6f6fde3b-7942-4530-8348-7105886b82bc.png)
2. I change to another opened file in VS Code
3. I change back to the 1st file and the Bookmark appears:
![image](https://user-images.githubusercontent.com/8282673/128486700-2da98798-3bf8-434c-94ab-5b0efd84212d.png)

Thanks a lot for your great support!
kind regards,
Thomas

**Comment by alefragnani** [comment] 2021-10-25 00:53
Hi @stellarwebworks ,

Are you still facing this issue? It’s been a while and not only Bookmarks but also VS Code released new versions, so I was wondering if you still have issues with the Side bar icon.

@schittli , I guess your issue is different, because _the icon appears after a while_. Probably related to #328 or #397. If not, please open a new issue with as much detail as possible.

Thank you

**Comment by deangibson89** [comment] 2022-01-25 09:28
Same problem, the bookmark icon isn't displaying in the side bar. Doesn't seem like it's just the icon that's missing, there is no clickable area that opens the sidebar. I've tried everything to no avail. Such a pity, this was hands down one of my most useful plugins I used.

**Comment by alefragnani** [comment] 2022-01-28 00:44
No success reproducing this error. For me, both Stable and Insiders are working just fine, up until now.

@deangibson89 , up until now, all reports say that _the icon is missing but the area is clickable_, so your is a bit different. Try using the `Bookmarks: Focus on Explorer View`. It should make VS Code focus on Bookmarks view/panel, no matter where it is located. Maybe it is not where it should be.

**Comment by alefragnani** [comment] 2022-08-02 01:01
I'm closing this issue because no new comments has been added since my last question. 
Feel free to reopen/comment if the error still occurs.

Thanks for your understanding

**Closed by alefragnani** 2022-08-02 01:01 UTC
Labels: bug, need more info

**Comment by mmcgee-aya** [comment] 2023-02-10 16:52
This is a still a problem for me at this point!!

**Comment by RodionovGV** [comment] 2024-02-20 02:18
I faced this problem too and found that bookmarks are available in the secondary sidebar (Ctrl+Alt+B).

**Comment by danigiorgio** [comment] 2024-08-08 20:38
This worked for me on Mac to show separate icon for Bookmarks in the sidebar

Run the command "Reset View Locations" via Command Palette (Command + Shift + P)
