### ISSUE TITLE
Icon missing?

### ISSUE THREAD

**Issue by fbnlsr** [alefragnani/vscode-bookmarks#170] opened 2019-01-10 14:50 UTC
As shown in the following screenshot, the Bookmarks icon is not showing in the leftmost bar?

![screenshot 2019-01-10 at 15 48 30](https://user-images.githubusercontent.com/1923346/50976120-77228100-14ef-11e9-9d25-b4d9d76f4937.jpg)

I tried with other themes, but no dice.

**Comment by alefragnani** [comment] 2019-01-10 20:42
Hi @fbnlsr ,

It appears a duplicate of #160 .

Yep, I have noted that too sometimes, but not only on my extension, but on Docker, GitLens and PowerShell as well. It seems to be an issue caused by VS Code, not the extension itself. In my case, it happens once and if I restart VS Code (Close and Open Again) the icon returns. At least once, I have to uninstall and reinstall the extension

Hope this helps

**Closed** 2019-01-10 20:42 UTC
Labels: activity bar, bug, caused by vscode, duplicate

**Comment by fbnlsr** [comment] 2019-01-11 11:49
Thanks a lot for your reply. Restarting VSCode did the trick indeed. Can't believe I haven't thought about that first.
