### ISSUE TITLE
Bookmark on the right editor opened the same file on the left

### ISSUE THREAD

**Issue by ThisIsManta** [alefragnani/vscode-bookmarks#74] opened 2017-06-09 06:45 UTC
**Steps to reproduce:**
1. Open file A on the left
2. Open file B on the right
3. Toggle a bookmark in file B

Notice that file B is _unexpectedly_ opened on the left.

**Comment by alefragnani** [comment] 2017-06-09 21:19
Hi @ThisIsManta  @freMea ,

This is probably related to  #36. Let's hope not :smile: .

**Comment by alefragnani** [comment] 2017-06-17 14:52
The two issues are not related. Unfortunately, this was caused by #30, released in version 0.15.0. 

I will try to fix this, but it appears to be a VSCode API issue. Maybe a workaround or even disabling #30 until the API is updated.

**Comment by alefragnani** [comment] 2017-06-17 16:02
Could be fixed without losing anything :)

Stay tuned for a new release.

**Closed** 2017-06-17 16:07 UTC
Labels: bug

**Comment by ThisIsManta** [comment] 2017-06-17 16:32
https://media.tenor.com/images/50aa2c4d5c28a64a0c14ec0b7cf81e12/tenor.gif
