### ISSUE TITLE
[Suggestion] Add notes to bookmarks

### ISSUE THREAD

**Issue by mfrsousa** [alefragnani/vscode-bookmarks#87] opened 2017-12-28 10:26 UTC
Sometimes we need to comment on the bookmarks without changing the files itself, maybe when we are working on somebody else's code

**Comment by alefragnani** [comment] 2017-12-28 16:20
Hi @mfrsousa ,

This is a duplicate of #76 . 

It's the next feature that I would like to add. I just have to _find some time_ 😄

**Closed by alefragnani** 2017-12-28 16:20 UTC
