### ISSUE TITLE
'Jump to Next' is jumping to other files

### ISSUE THREAD

**Issue by harryi3t** [alefragnani/vscode-bookmarks#132] opened 2018-07-23 07:51 UTC
I have a really big project will hundreds of files.
I have multiple bookmarks in many of them. When I am on one file and use the command `Jump to Next` it's opening a random file and taking me to a bookmark in that file.

Can we stop this behavior using some configuration?

Here's a gif that shows the bug
![vscode-bookmarks-bug-in-jumping](https://user-images.githubusercontent.com/5207331/43063963-277c8d8a-8e7b-11e8-918e-9900bb1a0f44.gif)

**Comment by alefragnani** [comment] 2018-07-23 22:35
Hi @harryi3t ,

This is a duplicate of #125 .

Thanks for reporting

**Closed** 2018-07-23 22:36 UTC
Labels: bug, duplicate
