### ISSUE TITLE
Keybindings should not be used under windows warning

### ISSUE THREAD

**Issue by con-ssc** [alefragnani/vscode-bookmarks#29] opened 2016-07-20 11:10 UTC
DevConsole logs following warnings with your extenstion

![image](https://cloud.githubusercontent.com/assets/8189808/16984592/3fa8af70-4e7b-11e6-8503-9d3af889f0a4.png)

![image](https://cloud.githubusercontent.com/assets/8189808/16984581/2b6d0966-4e7b-11e6-9484-91a4862d53bf.png)

**Comment by alefragnani** [comment] 2016-07-21 03:57
Hi @con-ssc ,

Unless you use a non-US keyboard layout, the extension works just fine. But I think I'll have to take a look at this soon, and change the default keybindings. This was already reported before, the first time in issue #13.

My concern, back in February, was about those that already had the extension installed and use the default keybindings, without any problem. If I change, they will be affected, so I have to find a way to avoid this. 

I was thinking, maybe to display a message right after updating the extension, asking if they want to keep the _old keybinding_, or replace with the new. Because only add this info in the `Readme` wouldn't be enough.

What do you think? And you @csholmq?

**Comment by con-ssc** [comment] 2016-07-21 06:55
@alefragnani I use a non-US keyboard, standard german logitechk 480 to be precise. Isn't there a way to register alternative keybindings? in the default key bindings mapping that is already done for other keyboard layouts.

**Comment by csholmq** [comment] 2016-07-21 07:36
@alefragnani Perhaps a setting to keep old keybindings? Either that or the user is forced to set his/her own keybindings.

**Comment by con-ssc** [comment] 2016-07-21 08:12
I meant something like this.
![image](https://cloud.githubusercontent.com/assets/8189808/17015645/98d759f6-4f2b-11e6-841b-3e185a5d7389.png)

**Comment by alefragnani** [comment] 2016-07-22 16:50
Duplicate of #13

**Closed by alefragnani** 2016-07-22 16:50 UTC
Labels: bug, duplicate
