### ISSUE TITLE
Extremely large files display error "Open a file to toggle bookmarks"

### ISSUE THREAD

**Issue by adamzl** [alefragnani/vscode-bookmarks#31] opened 2016-08-16 01:02 UTC
When attempting to use any of the bookmark commands on a very large file (100,000 lines anecdotally) an info popup appears at the top displaying the message: "Open a file first to toggle bookmarks".

My reproduction:

1. Open large file.
2. Attempt to toggle breakpoint
3. Failure message appears.
4. Create copy of the large file.
5. Cut the file down to 50 lines.
6. Save, close, reopen pruned copy.
7. Can now toggle breakpoints.

**Comment by alefragnani** [comment] 2016-08-16 02:11
Hi @adamzl ,

I could reproduce the problem 👍 . 

There seems to be an issue in VSCode core that erroneously says that there is no _ActiveText_. Unfortunatelly there is no workaround for that and I will have to report the problem to VSCode team, and wait for and alternative/solution, to have this fixed in the extension.

Thanks for repoting.

**Comment by alefragnani** [comment] 2016-08-23 00:24
It seems, based on [this VSCode issue](https://github.com/Microsoft/vscode/issues/3147), that this is _by design_, and large files will be invisible to extensions. 

Being so, there is no way to fix it, neither a workaround. 

Sorry about that.

**Closed** 2016-08-23 00:24 UTC
Labels: bug, wontfix

**Comment by adamzl** [comment] 2016-08-23 02:07
No worries, I'll always have Visual Studio for those monster-beast files.

**Comment by aplatypus** [comment] 2020-02-13 20:58
I have previously reported this System Failure and there are now many related issue reports al falling back to the Same Root Cause ...

*  VS Code wants to have all the file in memory

We deal with very large text files when dealing with production problems.  We have large data dumps, large log file sets, text based transaction snapshots and HTTP traffic, etc, etc.

It is essential that we have an edit tool that Can handle files as large a the (disk) storage capacity.  This is not some "new science", editors that can work on files bigger than memory have been around a very long time. 

What is most alarming is that a great many issues related to this are closed-off so there can be no input from end-users.  It is well that I don't have a tin-foil hat.

**Comment by alefragnani** [comment] 2020-05-16 19:20
Hi @aplatypus ,

The VS Code limitation still remains today. I understand your point, and I agree that "it should work", but I can't do anything about it. So, I suggest you to upvote/comment on VS Code repo issues that talks about it. 

I found at least 3:

* https://github.com/microsoft/vscode/issues/80056
* https://github.com/microsoft/vscode/issues/78394
* https://github.com/microsoft/vscode/issues/84940.

The good point is, when VS Code fixes this issue, I probably don't have to do anything on my side.
